### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by Not-February** [SammySemicolon/Omnis#1]
https://gist.github.com/Febilian/067c9e85242e745a71736151a12a35c0

`Forge 36.1.4`
`omnis-1.16.5-1.0`

**Comment by SammySemicolon** [comment]
Hey, thank u so much for letting me know of this problem <3 
I guess I forgot to check if the mod works on a server,,, Regardless, I fixed this issue and will fix more that popped up. 
Again, thanks for the info!

**Comment by SammySemicolon** [comment]
https://www.curseforge.com/minecraft/mc-mods/omnis/files/3274433
Here u go <3
