### ISSUE TITLE
[Crash] Dedicated Server Scythe Crash

### ISSUE THREAD

**Issue by SirOMGitsYOU** [SammySemicolon/Omnis#11]
Hi,

Ran into this issue on the latest version on 1.16.5 forge 36.2.35
[crash-2022-08-02_12.46.52-server.txt](https://github.com/SammySemicolon/Omnis/files/9242321/crash-2022-08-02_12.46.52-server.txt)

Issue occurred when one of our players hit a zombie with the scythe

**Comment by SammySemicolon** [comment]
Oi 
If I ever get around to updating the mod, I'll definitely fix this one. Sorry :P

**Comment by SirOMGitsYOU** [comment]
No worries :) we’ve disabled the recipe on the scythe(s) in our modpack to prevent others from having the issue!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SammySemicolon** [comment]
Fixed in 1.4
