### ISSUE TITLE
Omnis gives Savage and Ravage's Executioner a vindicator axe

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [SammySemicolon/Omnis#3]
Mod Versions:
Abnormals Core: 3.1.1
Savage and Ravage: 3.1.0
Omnis version: 1.1.1
Curios version: 4.0.5.1
Forge Version: 36.1.16

Hello!

First of all, I just wanted to say that I love this mod and the concepts behind it and I look forward to what you have planned for the future of this mod!

Secondly, I noticed an issue when testing this alongside Savage and Ravage (Which adds several new illager types) specifically in relation to an illager called the Executioner. I have noticed that when omnis is installed, the executioner's weapon is replaced by this mod's vindicator axe:
![2021-05-05_20 15 44](https://user-images.githubusercontent.com/64381954/117199320-f71c3580-ade1-11eb-8913-9cdd38ab75ca.png)
![2021-05-05_20 30 51](https://user-images.githubusercontent.com/64381954/117199382-0a2f0580-ade2-11eb-84c4-a9887fbff756.png)
This shouldn't be the case since Savage and Ravage adds a unique weapon specifically for this mob called the Cleaver of beheading which can only be obtained from this mob.  This issue therefore makes this weapon unobtainable.

My latest log can be found here: https://gist.github.com/NJL5390/a7fb34a8bc0f9d06d77401ba2f91a697

Thanks for the work you do on this mod! It has a bright future!

**Comment by SammySemicolon** [comment]
This actually brought up 2 issues, I may have forgotten to uncomment a line of code that makes the weapons only sometimes be given to their respective entities.
Thank you for posting the issue! <3

**Comment by The-Bernician-Lamb** [comment]
> This actually brought up 2 issues, I may have forgotten to uncomment a line of code that makes the weapons only sometimes be given to their respective entities.

I think you're right because some other things I've noticed with the recent update was that vindicators and vexes now always have their respective Omnis weapons and they always drop them when killed. (I meant to create separate issues for those but I forgot/ was busy Sorry)
