### ISSUE TITLE
Wisp Particle Crash / Conflict With Halogen

### ISSUE THREAD

**Issue by PhweeDev** [SammySemicolon/Omnis#7]
I got this weird crash when playing on my pack. It seems to be between Halogen and Omnis.
[crash-2022-01-15_11.55.31-client.txt](https://github.com/SammySemicolon/Omnis/files/7875505/crash-2022-01-15_11.55.31-client.txt

**Comment by SammySemicolon** [comment]
Yeah uhm, all you can do to fix this is remove halogen or not use the spellblade or vindicator axe at the moment. Once we move to 1.18 it'll be fixed.
