### ISSUE TITLE
[1.18.1] Gloomstone and possibly ravagestone don't have an appropriate harvest tool

### ISSUE THREAD

**Issue by Not-February** [SammySemicolon/Omnis#9]
Minecraft 1.18.1
Forge 39.1.2
Omnis 1.18.1-1.2

I've only actually tried with gloomstone but might want to check ravagestone too. It takes a long time to mine and you don't actually get it back with a pickaxe.

**Comment by SammySemicolon** [comment]
Oh my lord no WAY i forgot that

**Comment by SammySemicolon** [comment]
Like- I totally did, just, HOW do I forget that

**Comment by SammySemicolon** [comment]
Fixed in latest release
